[project]
name = "zaptecfaktura"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.120.2",
    "jinja2>=3.1.6",
    "python-jose[cryptography]>=3.5.0",
    "reportlab>=4.4.4",
]
